from app.admin.choice_disponibilidade_maquina import ChoiceDisponibilidadeMaquinaAdmin
from app.admin.choice_exame_coleta import ChoiceExameColetaAdmin
from app.admin.choice_periodo_turno import ChoicePeriodoTurnoAdmin
from app.admin.choice_teste_agua import ChoiceTesteAguaAdmin
from app.admin.choice_status_paciente import ChoiceStatusPaciente
from app.admin.controle_agua import ControleAguaAdmin
from app.admin.controle_coleta import ControleColetaAdmin
from app.admin.controle_desinfeccao import ControleDesinfeccaoAdmin
from app.admin.controle_financeiro import ControleFinanceiroAdmin
from app.admin.erro import ErroAdmin
from app.admin.estadia import EstadiaAdmin
from app.admin.manutencao_corretiva import ManutencaoCorretivaAdmin
from app.admin.manutencao_preventiva import ManutencaoPreventivaAdmin
from app.admin.maquina import MaquinaAdmin
from app.admin.paciente import PacienteAdmin
from app.admin.sala import SalaAdmin
from app.admin.secao import SecaoAdmin
