from app.admin.choice_disponibilidade_maquina import *
from app.admin.choice_exame_coleta import *
from app.admin.choice_periodo_turno import *
from app.admin.choice_teste_agua import *
from app.admin.controle_agua import *
from app.admin.controle_coleta import *
from app.admin.controle_desinfeccao import *
from app.admin.controle_financeiro import *
from app.admin.erro import *
from app.admin.estadia import *
from app.admin.manutencao_corretiva import *
from app.admin.manutencao_preventiva import *
from app.admin.maquina import *
from app.admin.sala import *
from app.admin.turno import *
