# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erro',
            name='estadia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erro', to='app.Estadia', verbose_name='Estadia'),
        ),
        migrations.AlterField(
            model_name='erro',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Maquina', verbose_name='Máquina'),
        ),
    ]
