# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-16 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlecoleta',
            name='data_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de envio'),
        ),
        migrations.AlterField(
            model_name='controlecoleta',
            name='data_realizado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de realização'),
        ),
        migrations.AlterField(
            model_name='controlecoleta',
            name='data_resultado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do resultado'),
        ),
        migrations.AlterField(
            model_name='controlecoleta',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ChoiceTesteAgua', verbose_name='Resultado'),
        ),
    ]
