# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-07 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='cpf',
        ),
    ]
