# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 13:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choiceperiodoturno',
            options={'verbose_name': 'Opção de período para seções', 'verbose_name_plural': 'Opções de período para seções'},
        ),
        migrations.AlterModelOptions(
            name='maquina',
            options={'ordering': ['erros', '-disponibilidade__identificador', '-criado'], 'verbose_name': 'Máquina', 'verbose_name_plural': 'Máquinas'},
        ),
        migrations.AlterField(
            model_name='erro',
            name='concluido',
            field=models.DateTimeField(blank=True, verbose_name='Concluído'),
        ),
        migrations.AlterField(
            model_name='erro',
            name='enfermeiro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enfermeiro'),
        ),
        migrations.AlterField(
            model_name='erro',
            name='estadia',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='erro', to='app.Estadia', verbose_name='Estadia'),
        ),
        migrations.AlterField(
            model_name='erro',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadias', to='app.Secao', verbose_name='Seção'),
        ),
    ]
