# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170515_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='disponibilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ChoiceDisponibilidadeMaquina', verbose_name='Disponibilidade'),
        ),
    ]
