# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170511_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencaocorretiva',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
            preserve_default=False,
        ),
    ]
