# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-16 23:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20170816_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='secao',
            name='enfermeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enfermeiro'),
        ),
    ]
