# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-07 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_paciente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(default='111.111.111-11', max_length=150, verbose_name='CPF'),
        ),
    ]
