# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170706_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erro',
            name='concluido',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluído'),
        ),
    ]
