# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170706_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erro',
            name='enfermeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enfermeiro'),
        ),
        migrations.AlterField(
            model_name='erro',
            name='estadia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erro', to='app.Estadia', verbose_name='Estadia'),
        ),
    ]
