# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 05:30
from __future__ import unicode_literals

import app.models.controle_agua
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_secao_enfermeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='desativado',
            field=models.BooleanField(default=False, verbose_name='Desativado'),
        ),
        migrations.AlterField(
            model_name='controleagua',
            name='arquivo_resultado',
            field=models.FileField(blank=True, upload_to=app.models.controle_agua.upload_to_path, verbose_name='Arquivo'),
        ),
    ]
