# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 19:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170515_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencaocorretiva',
            name='acao',
            field=models.TextField(blank=True, null=True, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='manutencaocorretiva',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='manutencaocorretiva',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Técnico'),
        ),
    ]
