# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-07 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_paciente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=150, unique=True, verbose_name='CPF'),
        ),
    ]
