# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170706_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='numero_da_maca',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número da maca'),
        ),
    ]
