# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170519_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='estadia',
            name='turno',
        ),
        migrations.AddField(
            model_name='estadia',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='estadia',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ChoicePeriodoTurno', verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='estadia',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='turno', to='app.Sala', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='numero_da_maca',
            field=models.IntegerField(default=0, verbose_name='Número da maca'),
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
