# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-15 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20171015_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlecoleta',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Técnico'),
        ),
    ]
