# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170707_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleFinanceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('ano', models.CharField(max_length=150, verbose_name='Ano')),
                ('convenio', models.CharField(max_length=150, verbose_name='Convênio')),
                ('janeiro', models.FloatField(blank=True, null=True, verbose_name='Janeiro')),
                ('fevereiro', models.FloatField(blank=True, null=True, verbose_name='Fevereiro')),
                ('marco', models.FloatField(blank=True, null=True, verbose_name='Março')),
                ('abril', models.FloatField(blank=True, null=True, verbose_name='Abril')),
                ('maio', models.FloatField(blank=True, null=True, verbose_name='Maio')),
                ('junho', models.FloatField(blank=True, null=True, verbose_name='Junho')),
                ('julho', models.FloatField(blank=True, null=True, verbose_name='Julho')),
                ('agosto', models.FloatField(blank=True, null=True, verbose_name='Agosto')),
                ('setembro', models.FloatField(blank=True, null=True, verbose_name='Setembro')),
                ('outubro', models.FloatField(blank=True, null=True, verbose_name='Outubro')),
                ('novembro', models.FloatField(blank=True, null=True, verbose_name='Novembro')),
                ('dezembro', models.FloatField(blank=True, null=True, verbose_name='Dezembro')),
            ],
            options={
                'verbose_name': 'Controle financeiro',
                'verbose_name_plural': 'Controle financeiro',
            },
        ),
        migrations.AlterModelOptions(
            name='estadia',
            options={'ordering': ['-secao__data', '-inicio', '-criado'], 'verbose_name': 'Estadia', 'verbose_name_plural': 'Estadias'},
        ),
    ]
