# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170519_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='data',
            field=models.DateTimeField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='numero_da_maca',
            field=models.IntegerField(verbose_name='Número da maca'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ChoicePeriodoTurno', verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sala', verbose_name='Sala'),
        ),
    ]
