# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170709_0337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlecoleta',
            options={'ordering': ['-data_realizado'], 'verbose_name': 'Controle de coleta', 'verbose_name_plural': 'Controle de coleta'},
        ),
        migrations.AlterModelOptions(
            name='erro',
            options={'ordering': ['-ocorrido'], 'verbose_name': 'Erro', 'verbose_name_plural': 'Erros'},
        ),
        migrations.AlterModelOptions(
            name='estadia',
            options={'ordering': ['-secao__data', '-inicio'], 'verbose_name': 'Estadia', 'verbose_name_plural': 'Estadias'},
        ),
        migrations.AlterModelOptions(
            name='manutencaocorretiva',
            options={'ordering': ['-criado'], 'verbose_name': 'Manutenção corretiva', 'verbose_name_plural': 'Manutenção corretiva'},
        ),
        migrations.AlterModelOptions(
            name='maquina',
            options={'ordering': ['-disponibilidade__identificador'], 'verbose_name': 'Máquina', 'verbose_name_plural': 'Máquinas'},
        ),
        migrations.AlterModelOptions(
            name='secao',
            options={'ordering': ['-data'], 'verbose_name': 'Seção', 'verbose_name_plural': 'Seções'},
        ),
    ]
