# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170522_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='data',
            field=models.DateTimeField(verbose_name='Data'),
        ),
    ]
