# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170522_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleagua',
            name='arquivo_resultado',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='controleagua',
            name='numero_do_laudo',
            field=models.IntegerField(default=0, verbose_name='Número do laudo'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='sala',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Sala', verbose_name='Disponibilidade'),
        ),
        migrations.AlterField(
            model_name='controleagua',
            name='resultado',
            field=models.BooleanField(default=False, verbose_name='Satisfatório'),
        ),
    ]
