# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170622_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('arquivo_resultado', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'TestModel',
                'verbose_name_plural': 'TestModels',
            },
        ),
    ]
