from app.views._index import *
from app.views.choice_disponibilidade_maquina import *
from app.views.choice_exame_coleta import *
from app.views.choice_periodo_turno import *
from app.views.choice_teste_agua import *
from app.views.controle_agua import *
from app.views.controle_coleta import *
from app.views.controle_desinfeccao import *
from app.views.controle_financeiro import *
from app.views.erro import *
from app.views.estadia import *
from app.views.manutencao_corretiva import *
from app.views.manutencao_preventiva import *
from app.views.maquina import *
from app.views.sala import *
from app.views.tecnico import *
from app.views.turno import *
